### ISSUE TITLE
POSTing textarea value

### ISSUE THREAD

**Issue by tvbarnette999** [tvbarnette999/nc-ftc-inspection#2]
@adwiii  When the fail button is presses, the note (the value of the textarea) is send via POST to the server. However, it seems to be loosing the FIRST two characters (refresh the page to see, also watch eclipse console). I have no idea whats going on. When I used the console in chrome to get the value through js it returned the whole string so it might be actually in the xhttp POST. You should look into this if you get bored.

**Comment by tvbarnette999** [comment]
The relevant js is the sendNote() function in fullUpdate.js

**Comment by adwiii** [comment]
So the problem is with Server.java:668. The POST that is made with the new system and old system. So for now, the code that is printed at 667 is correct for the new ones that use forms like hardware and software. Then something about the POST for the old system, like what sizing cube uses still, requires that you take off the first two chars. So since we are in between systems idk how to fix it, but thats what the issue is. The new system does not need the first two chars taken off, which the Server processing code is doing now.

**Comment by tvbarnette999** [comment]
This appeared again when POSTing signatures retrieved from a prompt. Continued with temporary solution and added "XX" to the beginning of the xhttp.send() parameter.

**Comment by adwiii** [comment]
Just so we know, I believe we have changed everywhere in the system to use "&&&" as the official escape sequence for everything in this program, both to solve this problem and as just a general purpose separator between data that we have already formatted. Note that no checking is done to escape a &&& sequence if the POST would otherwise contain one, and it is a known limitation in the system that sending &&& (either by entering it in a message or bad code) will cause unexpected behavior.
